// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserLogin struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

type UserIden struct {
	Id     int    `json:"id" db:"id"`
	RoleID string `json:"role_id" db:"role_id"`
}

type UserInfo struct {
	Username string `json:"username" db:"username"`
	Email    string `json:"email" db:"email"`
	RoleId   string `json:"role_id" db:"role_id"`
}

type UpdateUser struct {
	Username string `json:"username" db:"username"`
	Email    string `json:"email" db:"email"`
}
