// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"docker_gozero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/get",
					Handler: GetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/delete/:id",
					Handler: DeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
